# Generated by Django 5.0.6 on 2024-06-17 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productattribute_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, verbose_name='Variant title')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Variant Price')),
                ('sku', models.CharField(max_length=50, verbose_name='Variant SKU')),
                ('quantity', models.IntegerField(default=10, verbose_name='Variant quantity')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='product')),
            ],
        ),
    ]
