# Generated by Django 5.0.6 on 2024-06-17 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_productoption_variantoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variantoption',
            name='product',
        ),
        migrations.AddField(
            model_name='variantoption',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.variant', verbose_name='variant'),
        ),
    ]
