# Generated by Django 5.0.6 on 2024-06-18 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0005_rename_shipping_shopping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(verbose_name='Is successed')),
                ('tracking_id', models.CharField(max_length=100, verbose_name='Payment Getaway Tracking ID')),
                ('status', models.CharField(max_length=100, verbose_name='Order Status')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.order', verbose_name='Order')),
            ],
        ),
    ]
