# Generated by Django 5.0.6 on 2024-06-23 07:42

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_order_order_created_at_date_idx'),
        ('payment', '0003_alter_payment_order'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(django.db.models.functions.datetime.TruncDate('created_at'), models.F('created_at'), name='created_at_date_idx'),
        ),
    ]
