# Generated by Django 5.0.6 on 2024-06-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcard',
            name='is_primary',
            field=models.BooleanField(default=True, verbose_name='Is this the primary shopping cart?'),
        ),
    ]
