# Generated by Django 5.0.6 on 2024-06-17 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_shoppingcard_is_primary'),
        ('product', '0007_remove_variantoption_product_variantoption_variant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('craeted', 'Order Created'), ('cancled', 'Order cancled'), ('finished', 'Order finished'), ('proccessed', 'Order proccessed'), ('sent', 'Order sent'), ('deliverd', 'deliverd')], max_length=50, verbose_name='Order Status')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, verbose_name='Variant title')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Variant Price')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='Order')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.variant', verbose_name='Variant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
