# Generated by Django 5.0.6 on 2024-06-18 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_orderline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=254, verbose_name='User full addresses')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('postal_code', models.CharField(max_length=50, verbose_name='Postal Code')),
                ('recipient_name', models.CharField(max_length=100, verbose_name='Recipient Name')),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Location Latitude')),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Location Longitude')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='Order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
