# Generated by Django 5.0.6 on 2024-06-18 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_shipping'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shipping',
            new_name='Shopping',
        ),
    ]
