# Generated by Django 5.0.6 on 2024-06-23 07:42

import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_orderline_created_at_orderline_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(django.db.models.functions.datetime.TruncDate('created_at'), models.F('created_at'), name='order_created_at_date_idx'),
        ),
    ]
